inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  SuggestExtensions: false

  NewCops: enable

  DisplayCopNames: true

  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "lib/tasks/auto_annotate_models.rake"
    - "config/environments/*"
    - "config/puma.rb"
    - "config/initializers/*"
    - "spec/*"
    - "spec/factories/*"

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/AsciiComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Rails/ActionOrder:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/NegatedIfElseCondition:
  Enabled: false
